# Generated by Django 2.2 on 2021-04-23 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.IntegerField(null=True)),
                ('telpon', models.IntegerField(null=True)),
                ('jabatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pegawai.Jabatan')),
            ],
        ),
    ]
