# Generated by Django 2.2 on 2021-04-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
