# Generated by Django 2.2 on 2021-04-23 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_pegawai_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pegawai.Jabatan'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='nip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='telpon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
