# Generated by Django 2.2 on 2021-04-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0006_auto_20210423_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='status',
            field=models.CharField(choices=[('ASN', 'ASN'), ('PHL', 'PHL')], max_length=200, null=True),
        ),
    ]
