# Generated by Django 2.2 on 2021-04-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='didik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='goldarah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='jkel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='kagama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='kerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='skawin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stinggal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Penduduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kk', models.IntegerField(null=True)),
                ('nik', models.IntegerField(null=True)),
                ('nama', models.CharField(max_length=50)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('rt', models.IntegerField(null=True)),
                ('rw', models.IntegerField(null=True)),
                ('kelurahan', models.CharField(max_length=50)),
                ('agama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_penduduk.kagama')),
                ('gol_darah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_penduduk.goldarah')),
                ('jenis_kelamin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_penduduk.jkel')),
                ('pekerjaan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_penduduk.kerja')),
                ('pendidikan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_penduduk.didik')),
                ('status_kawin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_penduduk.skawin')),
                ('status_tinggal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_penduduk.stinggal')),
            ],
        ),
    ]
