# Generated by Django 2.2 on 2021-04-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_penduduk', '0002_jabatan_pegawai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='jabatan',
        ),
        migrations.DeleteModel(
            name='Jabatan',
        ),
        migrations.DeleteModel(
            name='Pegawai',
        ),
    ]
